### ISSUE TITLE
Possible to always show time?

### ISSUE THREAD

**Issue by Psychoboy** [tetrapus/PoGoPebble#5]
Is it possible to always display the current time? Maybe as an optional feature since it does operate as a watch face would still be nice to have the watch functionality.

**Comment by tetrapus** [comment]
Shake your wrist twice to show the current date and time below the pokemon.

The next release will change this so that it will show the time by default and the distance when you shake your wrist, and I'll release a watchapp version that has the old shake to toggle feature.
